### ISSUE TITLE
Compile it?

### ISSUE THREAD

**Issue by Resoluciones** [mbax/DisguiseCraft#2]
Hi! Great plugin!

Would it be possible someone compile it against last spigot or paper in a  .jar file?

Thank you!!!!

**Comment by mbax** [comment]
Hi there!

This is a six year old copy of the code, which isn't even my plugin.

Also, Bukkit died 4 years ago and any modern-built Spigot or Paper is violating US copyright law.

So, sorry but no :)


Check out [Sponge](https://www.spongepowered.org/) instead for a better and legal server experience.
